steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/fleet-blend-469520-n7/quickbi-data-scraper', '-f', 'deploy/Dockerfile.quickbi', '.']
images:
  - 'gcr.io/fleet-blend-469520-n7/quickbi-data-scraper'
